name: Republic
version: ${project.version}
main: homebrew.republic.Republic
api-version: 1.16
authors: [ Ryxian, HoneyBlocks]
description: ${project.description}
commands:
  party:
    usage: /<command>